format: yamanifest
version: 1.0
---
work/atmosphere/yatm_1bb8904.exe:
  fullpath: /g/data/ik11/inputs/access-om2/bin/yatm_1bb8904.exe
  hashes:
    binhash: f366cd63dda529d7f99d56b8764db757
    md5: 9e08e3e18873ce1a489020b89342c220
work/ice/cice_auscom_1440x1080_480p_d3e8bdf_libaccessom2_1bb8904.exe:
  fullpath: /g/data/ik11/inputs/access-om2/bin/cice_auscom_1440x1080_480p_d3e8bdf_libaccessom2_1bb8904.exe
  hashes:
    binhash: 0c207742fb5fb2b2ca8745f691484ac1
    md5: 5c96a5ec1d1cb38eff4cc977d8094be3
work/ocean/fms_ACCESS-OM_ce6567d_libaccessom2_1bb8904.x:
  fullpath: /g/data/e14/rmh561/access-om2/bin/fms_ACCESS-OM_ce6567d_libaccessom2_1bb8904.x
  hashes:
    binhash: f5170ce7e51b388a360e869abfb46e5f
    md5: 80cb3710a8a10746998506f8f6941faf
