format: yamanifest
version: 1.0
---
work/atmosphere/yatm_1bb8904.exe:
  fullpath: /g/data4/ik11/inputs/access-om2/bin/yatm_1bb8904.exe
  hashes:
    binhash: f366cd63dda529d7f99d56b8764db757
    md5: 9e08e3e18873ce1a489020b89342c220
work/ice/cice_auscom_1440x1080_480p_d3e8bdf_libaccessom2_1bb8904.exe:
  fullpath: /g/data4/ik11/inputs/access-om2/bin/cice_auscom_1440x1080_480p_d3e8bdf_libaccessom2_1bb8904.exe
  hashes:
    binhash: 0c207742fb5fb2b2ca8745f691484ac1
    md5: 5c96a5ec1d1cb38eff4cc977d8094be3
work/ocean/fms_ACCESS-OM_97e3429_libaccessom2_1bb8904.x:
  fullpath: /g/data4/ik11/inputs/access-om2/bin/fms_ACCESS-OM_97e3429_libaccessom2_1bb8904.x
  hashes:
    binhash: 4e751f42e9e04c7bb1e5e4b4a64a8185
    md5: 3d9ccce3eb68ea124f5a16d6cf0ddf1d
