format: yamanifest
version: 1.0
---
work/INPUT/ERA5_MOM025_patch.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/remap/prod/ERA5_MOM025_patch.nc
  hashes:
    binhash: 87bf203899401cdaceac20c9019c028a
    md5: efa945034d2b5b992e9f94474c8d914c
work/INPUT/ERA5_MOM1_patch.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/remap/prod/ERA5_MOM1_patch.nc
  hashes:
    binhash: 57aa08f3996d5590f21805b04008c79e
    md5: 5ffdf77bb57e10e3ede874752e4f6c6d
work/atmosphere/INPUT/RYF.10u.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.10u.1990_1991.nc
  hashes:
    binhash: eaf3e5d1b8e4a8633ef54de22382ba9e
    md5: 0ff212e5e82dc3ab0151c6e2069e5bf8
work/atmosphere/INPUT/RYF.10v.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.10v.1990_1991.nc
  hashes:
    binhash: 0ada7b1cb532832ae35f2837e922f66c
    md5: da0ae5fadf32b787d2b5048a0c9f911d
work/atmosphere/INPUT/RYF.2d.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.2d.1990_1991.nc
  hashes:
    binhash: 0c04ef8487ea8b34ecb321c1b60835c9
    md5: 31c1a526ee572508fafcdfa1835e2695
work/atmosphere/INPUT/RYF.2t.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.2t.1990_1991.nc
  hashes:
    binhash: 30e72a29859ebaec247ce4e16803b970
    md5: 8df68661f8bcad3b3533e49599e8386b
work/atmosphere/INPUT/RYF.crr.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.crr.1990_1991.nc
  hashes:
    binhash: 7ae13e0e38be3fbad720f7d4e03bc733
    md5: 4aaba1732bde97d2ff4a7384db98a1a9
work/atmosphere/INPUT/RYF.friver.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.friver.1990_1991.nc
  hashes:
    binhash: 9d237c730e295fd2a3515fe460bc59b3
    md5: fa3a55aeb6706a1b422d096f61a772c1
work/atmosphere/INPUT/RYF.licalvf.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.licalvf.1990_1991.nc
  hashes:
    binhash: eda4ced13dd1efc3c36bdb47a8945860
    md5: 6f927702cbc023cc20d3ddd69695f0a0
work/atmosphere/INPUT/RYF.lsrr.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.lsrr.1990_1991.nc
  hashes:
    binhash: d82fbc85409c6f2e2eb852c926263cf0
    md5: a192ab5a83c720bf61c161bb25052ed5
work/atmosphere/INPUT/RYF.msdwlwrf.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.msdwlwrf.1990_1991.nc
  hashes:
    binhash: 3c7d30260615eba2ebe730b292836d4e
    md5: e9cb192129f68ba4d33f0f7e933b1042
work/atmosphere/INPUT/RYF.msdwswrf.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.msdwswrf.1990_1991.nc
  hashes:
    binhash: bda09486e587a65fee6ce5c2194c42ae
    md5: c6dfe6156d93ffbf301031ca23ee0b55
work/atmosphere/INPUT/RYF.msl.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.msl.1990_1991.nc
  hashes:
    binhash: 973ac82bddd71300eab2c883bebe420d
    md5: 8bc22ecd4302088b2ee4ed1b64ab5001
work/atmosphere/INPUT/RYF.msr.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.msr.1990_1991.nc
  hashes:
    binhash: fd5ec79af30b41cc151623de8e8b1abe
    md5: 086c816a998305aefe0f4bf971d6a3d7
work/atmosphere/INPUT/RYF.sp.1990_1991.nc:
  fullpath: /g/data/e14/rmh561/access-om2/input/ERA-5/RYF/chunked/RYF.sp.1990_1991.nc
  hashes:
    binhash: e03e215331760d1fa87b4029a87dd682
    md5: 9ed21199287047166dc2324778a40648
work/atmosphere/INPUT/rmp_jrar_to_cict_CONSERV.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/yatm_025deg/rmp_jrar_to_cict_CONSERV.nc
  hashes:
    binhash: 5c9dc38068da3431afd3aa342bebbbcc
    md5: 2e8cf1844fe7a1156ef47170a6eb5ef1
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/cice_025deg/grid.nc
  hashes:
    binhash: ef32f5ea0beca45e4aaf2f4833b339d0
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/cice_025deg/i2o.nc
  hashes:
    binhash: 169a43590d8b0c812af3d993c4f65e8c
    md5: ca16c9eef58814b9ff13fd5e8bd88a25
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/cice_025deg/kmt.nc
  hashes:
    binhash: 01227be8425456ad64f9973e5ffaccbd
    md5: 576e78b474c37f61a6fb45c9f5692bc6
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/cice_025deg/monthly_sstsss.nc
  hashes:
    binhash: 2fdf1798189b37092a239c9c947d9d26
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/cice_025deg/o2i.nc
  hashes:
    binhash: 29b684d1cc141deb8f4bc69a47c12801
    md5: 5c695c6a91b4a2f64e653a5baa62c34a
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/cice_025deg/u_star.nc
  hashes:
    binhash: d0496680b0c663575627c6b13cdde39a
    md5: 4be7800aa8e310a6c7a9c3af1d50c7f0
work/ocean/INPUT/chl.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/chl.nc
  hashes:
    binhash: 3f04f0d65acdcd3b372792a41a268a3b
    md5: 99b68aec777292d746e4d93c2b976189
work/ocean/INPUT/grid_spec.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/grid_spec.nc
  hashes:
    binhash: ae901d0f717e53515ca692138e02f264
    md5: 57663e6575e424cce2cf98bc9778786a
work/ocean/INPUT/mask_table.465.48x40:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/mask_table.465.48x40
  hashes:
    binhash: 78890536cf18e166ab321c735bfb3d98
    md5: 10be6631aa435160b4d36531a4f6fd64
work/ocean/INPUT/ocean_hgrid.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/ocean_hgrid.nc
  hashes:
    binhash: e9be93a3cf26a195384ee3bc05bd7092
    md5: 38b6f324ae16cc13c180699123ad85b5
work/ocean/INPUT/ocean_mask.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/ocean_mask.nc
  hashes:
    binhash: be9a9fee69a77e01905aa46033997d19
    md5: 238bb01f653ae8a22a7efea4abda5442
work/ocean/INPUT/ocean_mask_table:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/ocean_mask_table
  hashes:
    binhash: e2d8c0480d04f17bfd2f18c6a2442fd7
    md5: 10be6631aa435160b4d36531a4f6fd64
work/ocean/INPUT/ocean_mosaic.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/ocean_mosaic.nc
  hashes:
    binhash: d6a322921d55b3f2c513b41140419110
    md5: 36e956159508785d9201cc13aec0cf02
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/ocean_temp_salt.res.nc
  hashes:
    binhash: aad91ea4d65dd96c5bff35831dec88e1
    md5: 1797b25e6339595a320076080145fd5a
work/ocean/INPUT/ocean_vgrid.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/ocean_vgrid.nc
  hashes:
    binhash: 686f94c85f81b4f8ece467b6b75436e1
    md5: e56e2936499d3ad53429d5940821118d
work/ocean/INPUT/roughness_amp.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/roughness_amp.nc
  hashes:
    binhash: 5c1446b38f847078524d0c7bd9a28f3a
    md5: 6b18885d65950d7ee2afe803432fbf5c
work/ocean/INPUT/roughness_cdbot.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/roughness_cdbot.nc
  hashes:
    binhash: 725ac7778f8de3b161e629a8870c9835
    md5: efa8999e9e4686cad695ff5cf0d523d5
work/ocean/INPUT/salt_sfc_restore.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/salt_sfc_restore.nc
  hashes:
    binhash: 59af4727ac218e7bc655dcbe583d8957
    md5: 434b4bdb323d17e9714d02519627fea2
work/ocean/INPUT/tideamp.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/tideamp.nc
  hashes:
    binhash: 15f0f0b212c93c48b02bcc4fa1113e3f
    md5: 49b1f91341f19cd4ef80a6be2cb2d250
work/ocean/INPUT/topog.nc:
  fullpath: /g/data/ik11/inputs/access-om2/input_20201102/mom_025deg/topog.nc
  hashes:
    binhash: 403068c883c2929190bbaf96ea711c80
    md5: bd08b1618377bf74309c52207e44be17
