format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/accessom2_restart.nml
  hashes:
    binhash: 1c310caa4b5733855f3e70354eac6e41
    md5: fa6419f3519469384a4b88a5434d1c56
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/grid.nc
  hashes:
    binhash: 4c778aee32fd0667aeda47ebf5df58b1
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/i2o.nc
  hashes:
    binhash: 4e9662ba32c8a93ab8a0dcad3dc18164
    md5: 9f747b4c4f608fd8a52e492e16a5ec25
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/ice.restart_file
  hashes:
    binhash: f4b8ff99c10f1dd53a5c2995fa3935aa
    md5: b496ed91e5704f89aac44da24a88a76b
work/ice/RESTART/iced.2301-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/iced.2301-01-01-00000.nc
  hashes:
    binhash: 6d2195b273aa362a3fb58f2035313a98
    md5: 1870fb2c7edeeb632da704beb3deaebf
work/ice/RESTART/iced.2302-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/iced.2302-01-01-00000.nc
  hashes:
    binhash: 889bd99b8f1f86cd98931977e7b8dbaa
    md5: 1d489f55720d72f6b5e2c32853158b51
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/kmt.nc
  hashes:
    binhash: 7d3c06f3662fb6c22e4611752a857fc1
    md5: 73d65aaee8da5caa8786963866ddc375
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/mice.nc
  hashes:
    binhash: d6d64ea84cef3b3dadced6c9f0c82ae3
    md5: 81bb9d4ce5524952e10a4233ad1ce912
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/monthly_sstsss.nc
  hashes:
    binhash: ea6d856a64c6b8b980132d14a618ad69
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/o2i.nc
  hashes:
    binhash: 01936337497a30be042534801f027e8b
    md5: 21f2988abc72b292255cfd5f05eefab9
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/sicemass.nc
  hashes:
    binhash: 1ab0f2edcbb7deb3fe77841d6130e5ce
    md5: 9a93562a9177337af809f806c36e3c63
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ice/u_star.nc
  hashes:
    binhash: 4a2af1e1f6a8836ae37cfc5f090d8488
    md5: 4cbe15c12a6b708fac78f1ba807640af
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_age.res.nc
  hashes:
    binhash: b2ef5083d73529067c1a603f57b796f6
    md5: 41d5269b36cb18217ffb3fc78f9033c6
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: cd29757078bcb1dd1e0f2957cb3cc337
    md5: c2cc1b70d59be840e287559e2bdb741e
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: ff5bb0da1fbaeb5fe4c98610a45d46aa
    md5: f8819aeb78102d2ea69b56046e6cf19c
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_density.res.nc
  hashes:
    binhash: 310b29dc33821ea6ba1418e8afe1b5e3
    md5: cafa943bb6b335091e8aa657c61f0676
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 667028fbe38a4d2332746612811c13bd
    md5: eb13b04003addfb28b29611fdb90b97e
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 2046af6365813945b8d2ea462b75710f
    md5: d5caad888dd00704d7864450765a4cbb
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: cce8d4f014d0ea490ab08cbf9cf8bea2
    md5: 2412e5d84f66dd2a74fedd084c519e9c
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 233c4d01efc8fc09042234ed0a2156c1
    md5: 14991356c39f2ed77cdfe31e07c5b88c
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_solo.res
  hashes:
    binhash: ca11626f80b647e5f9f5f2520c7ac783
    md5: 9f12928d6d22a2738af23daae4564014
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cdb2343fc44e47c90a77add2aaecb946
    md5: a1106c2c81cb260ec5e3f4ee1c311e8c
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_thickness.res.nc
  hashes:
    binhash: b8297c0ccc094a3c0674bff532c8c37d
    md5: ba6d2ba95d22b755ded6f997a8a3d37c
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_tracer.res
  hashes:
    binhash: 98b35ce738c5a66923d35d3dd103be3b
    md5: 537a2426373359519aaa012ee893c98a
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 0f85f2243eb69adf997b80d3ea538a84
    md5: 8bcd17e0608e2c13eb34a1d9775009cf
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55_ryf_1Kv/restart200/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 1a6a3962b2d7c7ad8097692c36c6a494
    md5: 2a39c10a8d4473c924c8b178a6502549
